services:
  backend:
    build:
      context: ./backend
    container_name: bowatt-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - bo_network

  frontend:
    build:
      context: ./frontend
    container_name: bowatt-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bo_network

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bo_network

networks:
  bo_network:
