# backend/.air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  log = "build.log"

[log]
  time = true
